version: "3"

services:
  db:
    image: postgres
    networks:
      - sonarnet
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - ~/dev/sonarqube/postgresql:/var/lib/postgresql
      - ~/dev/sonarqube/postgresql/data:/var/lib/postgresql/data
  sonarqube:
    image: sonarqube:8.8-community
    depends_on:
      - db
    ports:
      - "9000:9000"
    networks:
      - sonarnet
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - ~/dev/sonarqube/data:/opt/sonarqube/data
      - ~/dev/sonarqube/extensions:/opt/sonarqube/extensions
      - ~/dev/sonarqube/logs:/opt/sonarqube/logs
      - ~/dev/sonarqube/temp:/opt/sonarqube/temp

networks:
  sonarnet:
    driver: bridge
